"""Initial migration

Revision ID: 42355a96f17f
Revises: 
Create Date: 2025-12-31 18:23:54.925622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42355a96f17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookarchive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookarchive',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookarchive'))
    )
    # ### end Alembic commands ###
